export const SEED_SPECIALTIES = [
  {
    id: 'spec-cardio',
    name: 'Cardiology',
    slug: 'cardiology',
    iconName: 'Heart',
    description: 'Comprehensive cardiovascular care, ECG, echo, hypertension, and coronary artery disease management.',
    commonSymptoms: ['Chest pain', 'Palpitations', 'Shortness of breath', 'High blood pressure', 'Dizziness']
  },
  {
    id: 'spec-neuro',
    name: 'Neurology & Neurosurgery',
    slug: 'neurology',
    iconName: 'Brain',
    description: 'Advanced neurological disorders, epilepsy, migraine, stroke rehabilitation, and spinal health.',
    commonSymptoms: ['Severe headaches', 'Numbness or tingling', 'Tremors', 'Seizures', 'Memory loss']
  },
  {
    id: 'spec-ortho',
    name: 'Orthopedics & Joint Care',
    slug: 'orthopedics',
    iconName: 'Activity',
    description: 'Robotic joint replacement, sports injury rehab, arthroscopy, and fracture management.',
    commonSymptoms: ['Knee pain', 'Backache', 'Joint stiffness', 'Fracture', 'Sports injury']
  },
  {
    id: 'spec-pedia',
    name: 'Pediatrics & Neonatology',
    slug: 'pediatrics',
    iconName: 'Baby',
    description: 'Child health, immunization schedules, newborn intensive care, and developmental tracking.',
    commonSymptoms: ['Childhood fever', 'Cough & cold', 'Delayed milestones', 'Growth concerns', 'Vaccination']
  },
  {
    id: 'spec-derma',
    name: 'Dermatology & Cosmetology',
    slug: 'dermatology',
    iconName: 'Sparkles',
    description: 'Clinical skin therapy, acne, eczema, psoriasis, and laser dermatological procedures.',
    commonSymptoms: ['Skin rash', 'Acne & scars', 'Hair loss', 'Skin pigmentation', 'Itching']
  },
  {
    id: 'spec-onco',
    name: 'Medical & Surgical Oncology',
    slug: 'oncology',
    iconName: 'Shield',
    description: 'Multi-disciplinary cancer therapy, precision chemotherapy, and oncological surgeries.',
    commonSymptoms: ['Unexplained weight loss', 'Persistent lump', 'Chronic fatigue', 'Abnormal bleeding']
  },
  {
    id: 'spec-gynae',
    name: 'Obstetrics & Gynecology',
    slug: 'gynecology',
    iconName: 'Users',
    description: 'Maternity care, high-risk pregnancy, women\'s wellness, and reproductive health.',
    commonSymptoms: ['Irregular periods', 'Pelvic pain', 'Pregnancy checkup', 'PCOS', 'Menopause symptoms']
  },
  {
    id: 'spec-gastro',
    name: 'Gastroenterology & Hepatology',
    slug: 'gastroenterology',
    iconName: 'Stethoscope',
    description: 'Digestive tract disorders, liver clinics, therapeutic endoscopy, and reflux management.',
    commonSymptoms: ['Acid reflux & heartburn', 'Stomach bloating', 'Jaundice', 'Constipation', 'Abdominal cramps']
  },
  {
    id: 'spec-pulmo',
    name: 'Pulmonology & Chest Medicine',
    slug: 'pulmonology',
    iconName: 'Wind',
    description: 'Asthma, chronic bronchitis, post-viral pulmonary recovery, and sleep apnea diagnostics.',
    commonSymptoms: ['Chronic cough', 'Wheezing', 'Breathlessness', 'Chest congestion', 'Snoring / sleep apnea']
  },
  {
    id: 'spec-genmed',
    name: 'Internal & General Medicine',
    slug: 'general-medicine',
    iconName: 'UserCheck',
    description: 'Primary medical care, diabetes, infectious diseases, preventive health checks, and wellness.',
    commonSymptoms: ['Fever & chills', 'Fatigue & weakness', 'Diabetes check', 'Hypertension', 'Body aches']
  }
];

export const SEED_HOSPITALS = [
  {
    id: 'hosp-01',
    name: 'CareBridge Apex Super-Specialty Hospital',
    type: 'Super-Specialty Tertiary Hospital',
    tagline: 'Centre of Excellence in Cardiac & Neuro Sciences',
    overview: 'CareBridge Apex Hospital is a premier 650-bed quaternary care hospital featuring state-of-the-art cath labs, robotic surgical suites, and dedicated 24x7 trauma & emergency wards.',
    imageUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800&auto=format&fit=crop&q=80',
    address: '42 Outer Ring Road, Bellandur',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560103',
    coordinates: { lat: 12.9298, lng: 77.6848 },
    distanceKm: 1.2,
    phone: '+91 80 4910 2000',
    emergencyContact: '1066 / +91 80 4910 2911',
    emergency24x7: true,
    icuBeds: 120,
    openingHours: '24 Hours / 7 Days',
    rating: 4.88,
    reviewCount: 1420,
    departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Oncology', 'Emergency Care', 'Gastroenterology'],
    services: ['24x7 Emergency & Trauma', 'Robotic Knee Replacement', 'PET-CT & 3T MRI', 'NABH Accredited Blood Bank', 'Organ Transplant Suite'],
    featuredDoctorIds: ['doc-sharma', 'doc-patel']
  },
  {
    id: 'hosp-02',
    name: 'CareBridge Heart & Trauma Institute',
    type: 'Multi-Specialty Tertiary Hospital',
    tagline: 'Rapid Response Emergency & Cardiovascular Care',
    overview: 'Equipped with dedicated acute myocardial infarction rapid protocols, Level-1 trauma bays, and 85 high-dependency intensive care beds.',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
    address: '112 Anna Salai, Teynampet',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600018',
    coordinates: { lat: 13.0418, lng: 80.2507 },
    distanceKm: 3.4,
    phone: '+91 44 2430 8000',
    emergencyContact: '1066 / +91 44 2430 8911',
    emergency24x7: true,
    icuBeds: 85,
    openingHours: '24 Hours / 7 Days',
    rating: 4.82,
    reviewCount: 980,
    departments: ['Cardiology', 'Trauma & Emergency', 'Pulmonology', 'Critical Care', 'Internal Medicine'],
    services: ['Primary Angioplasty 24x7', 'Stroke Rapid Response Bay', 'Extracorporeal Life Support (ECMO)', 'Digital Dialysis Unit'],
    featuredDoctorIds: ['doc-gupta']
  },
  {
    id: 'hosp-03',
    name: 'CareBridge Women & Children\'s Pavilion',
    type: 'Specialized Mother & Child Hospital',
    tagline: 'Compassionate Maternity, Neonatal & Pediatric Care',
    overview: 'Specialized 280-bed hospital dedicated to maternal fetal medicine, Level-III NICU care, adolescent health, and advanced pediatric surgical procedures.',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80',
    address: '18 Institutional Area, Sheikh Sarai',
    district: 'South Delhi',
    state: 'Delhi',
    pincode: '110017',
    coordinates: { lat: 28.5355, lng: 77.2289 },
    distanceKm: 4.1,
    phone: '+91 11 4150 7000',
    emergencyContact: '1066 / +91 11 4150 7911',
    emergency24x7: true,
    icuBeds: 50,
    openingHours: '24 Hours / 7 Days',
    rating: 4.91,
    reviewCount: 860,
    departments: ['Pediatrics', 'Obstetrics & Gynecology', 'Neonatal ICU', 'Genetics & Fertility'],
    services: ['Level III Neonatal ICU', 'Laparoscopic Gynaecology', 'Fetal Medicine & 4D Ultrasound', 'Pediatric Emergency Unit'],
    featuredDoctorIds: ['doc-menon', 'doc-chatterjee']
  },
  {
    id: 'hosp-04',
    name: 'CareBridge Brain & Spine Institute',
    type: 'Super-Specialty Neuroscience Hospital',
    tagline: 'Precision Neuro-Interventions & Advanced Spine Surgery',
    overview: 'Comprehensive neuroscience facility featuring intra-operative neuro-monitoring, biplane neurovascular cath labs, and specialized stroke recovery therapy.',
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80',
    address: 'Road No. 2, Banjara Hills',
    district: 'Hyderabad',
    state: 'Telangana',
    pincode: '500034',
    coordinates: { lat: 17.4156, lng: 78.4350 },
    distanceKm: 2.7,
    phone: '+91 40 3350 4000',
    emergencyContact: '1066 / +91 40 3350 4911',
    emergency24x7: true,
    icuBeds: 70,
    openingHours: '24 Hours / 7 Days',
    rating: 4.86,
    reviewCount: 710,
    departments: ['Neurology', 'Neurosurgery', 'Spine Rehabilitation', 'Interventional Radiology'],
    services: ['24x7 Acute Stroke Thrombectomy', 'Minimally Invasive Spine Surgery', 'Epilepsy Monitoring Unit', 'Neuro-ICU Care'],
    featuredDoctorIds: ['doc-reddy']
  },
  {
    id: 'hosp-05',
    name: 'CareBridge Metro Multi-Specialty Hospital',
    type: 'Multi-Specialty Tertiary Hospital',
    tagline: 'Comprehensive Healthcare for the Metropolis',
    overview: 'A full-spectrum 520-bed tertiary facility serving Western India with world-class surgical oncology, orthopedic trauma, and digestive health institutes.',
    imageUrl: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&auto=format&fit=crop&q=80',
    address: 'Link Road, Andheri West',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    pincode: '400053',
    coordinates: { lat: 19.1363, lng: 72.8277 },
    distanceKm: 5.0,
    phone: '+91 22 6620 9000',
    emergencyContact: '1066 / +91 22 6620 9911',
    emergency24x7: true,
    icuBeds: 95,
    openingHours: '24 Hours / 7 Days',
    rating: 4.79,
    reviewCount: 1150,
    departments: ['Orthopedics', 'Gastroenterology', 'Cardiology', 'Internal Medicine', 'Emergency Care', 'Surgical Oncology'],
    services: ['Computer-Navigated Joint Surgery', 'Endoscopic Ultrasound (EUS)', 'Multidisciplinary Tumor Board', 'Daycare Chemotherapy'],
    featuredDoctorIds: ['doc-verma', 'doc-kulkarni']
  }
];

export const SEED_DOCTORS = [
  {
    id: 'doc-sharma',
    uid: 'doc-sharma',
    fullName: 'Dr. Anita Sharma',
    title: 'Senior Consultant - Interventional Cardiology',
    specialty: 'Cardiology',
    qualifications: 'MBBS, MD (Internal Medicine), DM (Cardiology), FACC',
    experienceYears: 15,
    registrationNumber: 'MCI/UP/2012/048821',
    councilName: 'Uttar Pradesh Medical Council',
    hospitalAffiliation: 'CareBridge Apex Super-Specialty Hospital',
    hospitalId: 'hosp-01',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    about: 'Dr. Anita Sharma is a renowned interventional cardiologist specializing in coronary artery disease, preventative cardiovascular risk assessment, and complex angioplasties.',
    areasOfExpertise: ['Coronary Angioplasty', 'Heart Failure Management', 'Preventive Cardiology', 'Echocardiography'],
    languages: ['English', 'Hindi', 'Kannada'],
    consultationFee: 800,
    rating: 4.92,
    reviewCount: 420,
    nextAvailableSlot: 'Today at 04:30 PM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: ['09:30 AM', '10:30 AM', '11:30 AM', '04:30 PM', '05:30 PM', '06:30 PM']
  },
  {
    id: 'doc-verma',
    uid: 'doc-verma',
    fullName: 'Dr. Rajesh Verma',
    title: 'Chief Consultant - Orthopedic & Joint Reconstruction',
    specialty: 'Orthopedics & Joint Care',
    qualifications: 'MBBS, MS (Orthopedics), MCh (Joint Reconstruction, UK)',
    experienceYears: 18,
    registrationNumber: 'NMC/2016/091244',
    councilName: 'National Medical Commission (NMC)',
    hospitalAffiliation: 'CareBridge Metro Multi-Specialty Hospital',
    hospitalId: 'hosp-05',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    about: 'Expert in primary and revision knee and hip arthroplasty, sports ligament reconstructions, and minimally invasive complex fracture fixation.',
    areasOfExpertise: ['Robotic Knee Replacement', 'Hip Arthroplasty', 'Arthroscopic Surgery', 'Complex Trauma'],
    languages: ['English', 'Hindi', 'Marathi'],
    consultationFee: 900,
    rating: 4.88,
    reviewCount: 380,
    nextAvailableSlot: 'Tomorrow at 10:00 AM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Mon', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: ['10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM']
  },
  {
    id: 'doc-menon',
    uid: 'doc-menon',
    fullName: 'Dr. Priya Menon',
    title: 'Lead Consultant - Pediatrics & Neonatology',
    specialty: 'Pediatrics & Neonatology',
    qualifications: 'MBBS, MD (Pediatrics), Fellowship in Neonatology (AIIMS)',
    experienceYears: 12,
    registrationNumber: 'KMC/2014/082190',
    councilName: 'Karnataka Medical Council',
    hospitalAffiliation: 'CareBridge Women & Children\'s Pavilion',
    hospitalId: 'hosp-03',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813684-2fbf0beea853?w=400&auto=format&fit=crop&q=80',
    about: 'Compassionate pediatric care focusing on pediatric infections, immunization schedules, infant nutrition, and child developmental milestones.',
    areasOfExpertise: ['Newborn Care', 'Pediatric Asthma', 'Vaccination Protocols', 'Growth & Nutrition'],
    languages: ['English', 'Hindi', 'Malayalam'],
    consultationFee: 650,
    rating: 4.95,
    reviewCount: 540,
    nextAvailableSlot: 'Today at 05:15 PM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '04:00 PM', '05:15 PM']
  },
  {
    id: 'doc-reddy',
    uid: 'doc-reddy',
    fullName: 'Dr. Arvind Reddy',
    title: 'Senior Consultant - Neurologist & Stroke Lead',
    specialty: 'Neurology & Neurosurgery',
    qualifications: 'MBBS, MD (General Medicine), DM (Neurology)',
    experienceYears: 20,
    registrationNumber: 'APMC/2005/019942',
    councilName: 'Andhra Pradesh Medical Council',
    hospitalAffiliation: 'CareBridge Brain & Spine Institute',
    hospitalId: 'hosp-04',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    about: 'Specialized in acute stroke interventions, Parkinson\'s management, refractory epilepsy care, and clinical neurophysiology.',
    areasOfExpertise: ['Stroke Thrombolysis', 'Epilepsy Management', 'Movement Disorders', 'Neuropathy'],
    languages: ['English', 'Telugu', 'Hindi'],
    consultationFee: 1100,
    rating: 4.91,
    reviewCount: 295,
    nextAvailableSlot: 'Tomorrow at 11:30 AM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: ['10:30 AM', '11:30 AM', '03:00 PM', '04:00 PM', '05:00 PM']
  },
  {
    id: 'doc-patel',
    uid: 'doc-patel',
    fullName: 'Dr. Meera Patel',
    title: 'Senior Consultant - Clinical & Aesthetic Dermatologist',
    specialty: 'Dermatology & Cosmetology',
    qualifications: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    experienceYears: 10,
    registrationNumber: 'GMMC/2015/063311',
    councilName: 'Gujarat Medical Council',
    hospitalAffiliation: 'CareBridge Apex Super-Specialty Hospital',
    hospitalId: 'hosp-01',
    avatarUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=400&auto=format&fit=crop&q=80',
    about: 'Expertise in chronic dermatitis, psoriasis biologic therapy, acne scar management, and evidence-based clinical dermatology.',
    areasOfExpertise: ['Clinical Dermatology', 'Psoriasis Clinic', 'Eczema & Allergy', 'Hair Loss Therapies'],
    languages: ['English', 'Gujarati', 'Hindi'],
    consultationFee: 600,
    rating: 4.86,
    reviewCount: 320,
    nextAvailableSlot: 'Today at 06:00 PM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat'],
    availableSlots: ['11:00 AM', '12:00 PM', '04:00 PM', '05:00 PM', '06:00 PM']
  },
  {
    id: 'doc-kulkarni',
    uid: 'doc-kulkarni',
    fullName: 'Dr. Vikram Kulkarni',
    title: 'Director - Surgical Oncology Services',
    specialty: 'Medical & Surgical Oncology',
    qualifications: 'MBBS, MS (General Surgery), MCh (Surgical Oncology, Tata Memorial)',
    experienceYears: 22,
    registrationNumber: 'MMC/2003/014490',
    councilName: 'Maharashtra Medical Council',
    hospitalAffiliation: 'CareBridge Metro Multi-Specialty Hospital',
    hospitalId: 'hosp-05',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
    about: 'Dedicated oncology surgeon specializing in gastrointestinal, breast, and thoracic oncological resections with organ preservation techniques.',
    areasOfExpertise: ['Breast Oncoplastic Surgery', 'GI Oncology', 'Thoracic Oncology', 'HIPEC Procedures'],
    languages: ['English', 'Marathi', 'Hindi'],
    consultationFee: 1500,
    rating: 4.93,
    reviewCount: 210,
    nextAvailableSlot: 'Thursday at 02:00 PM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    availableSlots: ['02:00 PM', '03:00 PM', '04:00 PM', '05:00 PM']
  },
  {
    id: 'doc-chatterjee',
    uid: 'doc-chatterjee',
    fullName: 'Dr. Sunita Chatterjee',
    title: 'Senior Consultant - Obstetrics & High-Risk Pregnancy',
    specialty: 'Obstetrics & Gynecology',
    qualifications: 'MBBS, MD (Obs & Gynae), FICOG',
    experienceYears: 16,
    registrationNumber: 'WBMC/2009/032210',
    councilName: 'West Bengal Medical Council',
    hospitalAffiliation: 'CareBridge Women & Children\'s Pavilion',
    hospitalId: 'hosp-03',
    avatarUrl: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=400&auto=format&fit=crop&q=80',
    about: 'Specializes in high-risk pregnancy monitoring, minimally invasive laparoscopic gynecological surgery, PCOS management, and adolescent healthcare.',
    areasOfExpertise: ['High-Risk Pregnancy', 'Laparoscopic Hysterectomy', 'PCOS & Infertility', 'Antenatal Screening'],
    languages: ['English', 'Bengali', 'Hindi'],
    consultationFee: 850,
    rating: 4.89,
    reviewCount: 470,
    nextAvailableSlot: 'Tomorrow at 09:30 AM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Sat'],
    availableSlots: ['09:30 AM', '10:30 AM', '11:30 AM', '03:30 PM', '04:30 PM']
  },
  {
    id: 'doc-gupta',
    uid: 'doc-gupta',
    fullName: 'Dr. Alok Gupta',
    title: 'Consultant Physician & Diabetologist',
    specialty: 'Internal & General Medicine',
    qualifications: 'MBBS, MD (General Medicine), PG Diploma in Diabetology',
    experienceYears: 14,
    registrationNumber: 'DMC/2011/055120',
    councilName: 'Delhi Medical Council',
    hospitalAffiliation: 'CareBridge Heart & Trauma Institute',
    hospitalId: 'hosp-02',
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&auto=format&fit=crop&q=80',
    about: 'Expert physician addressing metabolic disorders, glycemic control in diabetic patients, hypertension titration, and acute seasonal febrile illnesses.',
    areasOfExpertise: ['Type 2 Diabetes', 'Hypertension Control', 'Geriatric Care', 'Infectious Diseases'],
    languages: ['English', 'Hindi', 'Tamil'],
    consultationFee: 500,
    rating: 4.81,
    reviewCount: 395,
    nextAvailableSlot: 'Today at 03:30 PM',
    consultationModes: ['in_person', 'teleconsultation'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: ['09:00 AM', '10:00 AM', '02:30 PM', '03:30 PM', '04:30 PM']
  }
];

export const SEED_MEDICINES = [
  {
    id: 'med-01',
    brandName: 'Dolo 650',
    genericName: 'Paracetamol 650 mg',
    composition: 'Paracetamol IP 650mg',
    dosageForm: 'Tablet',
    strength: '650 mg',
    category: 'Pain & Analgesics',
    manufacturer: 'Micro Labs Ltd',
    price: 32.50,
    prescriptionRequired: false,
    usageInstructions: 'Take 1 tablet after meals every 6-8 hours as needed. Maximum 4 tablets in 24 hours.'
  },
  {
    id: 'med-02',
    brandName: 'Augmentin 625 Duo',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    composition: 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
    dosageForm: 'Tablet',
    strength: '625 mg',
    category: 'Antibiotics',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    price: 204.00,
    prescriptionRequired: true,
    usageInstructions: 'Take 1 tablet twice daily with meals for 5-7 days or as prescribed.'
  },
  {
    id: 'med-03',
    brandName: 'Glycomet 500 SR',
    genericName: 'Metformin Hydrochloride (Sustained Release)',
    composition: 'Metformin Hydrochloride IP 500mg',
    dosageForm: 'Tablet',
    strength: '500 mg',
    category: 'Diabetic Care',
    manufacturer: 'USV Private Limited',
    price: 48.00,
    prescriptionRequired: true,
    usageInstructions: 'Take 1 tablet with evening meals to minimize gastrointestinal discomfort.'
  },
  {
    id: 'med-04',
    brandName: 'Telma 40',
    genericName: 'Telmisartan 40 mg',
    composition: 'Telmisartan IP 40mg',
    dosageForm: 'Tablet',
    strength: '40 mg',
    category: 'Cardiovascular',
    manufacturer: 'Glenmark Pharmaceuticals',
    price: 125.00,
    prescriptionRequired: true,
    usageInstructions: 'Take 1 tablet once daily in the morning with or without water.'
  },
  {
    id: 'med-05',
    brandName: 'Pan 40',
    genericName: 'Pantoprazole Sodium Gastro-resistant',
    composition: 'Pantoprazole Sodium IP 40mg',
    dosageForm: 'Tablet',
    strength: '40 mg',
    category: 'Gastrointestinal',
    manufacturer: 'Alkem Laboratories Ltd',
    price: 142.50,
    prescriptionRequired: false,
    usageInstructions: 'Take 1 tablet empty stomach in the morning 30 minutes before breakfast.'
  },
  {
    id: 'med-06',
    brandName: 'Atorva 20',
    genericName: 'Atorvastatin 20 mg',
    composition: 'Atorvastatin Calcium IP 20mg',
    dosageForm: 'Tablet',
    strength: '20 mg',
    category: 'Cardiovascular',
    manufacturer: 'Zydus Cadila',
    price: 185.00,
    prescriptionRequired: true,
    usageInstructions: 'Take 1 tablet daily at night before sleep.'
  },
  {
    id: 'med-07',
    brandName: 'Montair LC',
    genericName: 'Montelukast + Levocetirizine',
    composition: 'Montelukast Sodium (10mg) + Levocetirizine HCl (5mg)',
    dosageForm: 'Tablet',
    strength: '10 mg + 5 mg',
    category: 'Respiratory & Allergy',
    manufacturer: 'Cipla Ltd',
    price: 198.00,
    prescriptionRequired: true,
    usageInstructions: 'Take 1 tablet once daily at bedtime.'
  },
  {
    id: 'med-08',
    brandName: 'Budecort 200 Inhaler',
    genericName: 'Budesonide Inhalation Aerosol',
    composition: 'Budesonide IP 200 mcg per actuation',
    dosageForm: 'Inhaler',
    strength: '200 mcg',
    category: 'Respiratory & Allergy',
    manufacturer: 'Cipla Ltd',
    price: 345.00,
    prescriptionRequired: true,
    usageInstructions: 'Inhale 1-2 puffs twice daily through spacer; rinse mouth thoroughly after inhalation.'
  },
  {
    id: 'med-09',
    brandName: 'Volini Gel',
    genericName: 'Diclofenac Diethylamine + Methyl Salicylate',
    composition: 'Diclofenac Diethylamine 1.16% w/w',
    dosageForm: 'Ointment',
    strength: '30 g',
    category: 'Pain & Analgesics',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    price: 110.00,
    prescriptionRequired: false,
    usageInstructions: 'Apply 3-4 times a day gently on the affected area. Wash hands after use.'
  },
  {
    id: 'med-10',
    brandName: 'Lantus Solostar Pen',
    genericName: 'Insulin Glargine',
    composition: 'Insulin Glargine 100 Units/ml',
    dosageForm: 'Injection',
    strength: '100 IU/ml',
    category: 'Diabetic Care',
    manufacturer: 'Sanofi India Ltd',
    price: 620.00,
    prescriptionRequired: true,
    usageInstructions: 'Inject subcutaneously once daily at the same time each day.'
  }
];

export const SEED_PHARMACIES = [
  {
    id: 'ph-01',
    name: 'CareBridge 24x7 In-Hospital Pharmacy',
    address: 'Ground Floor, CareBridge Apex Super-Specialty Hospital, Outer Ring Road',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560103',
    phone: '+91 80 4910 2150',
    coordinates: { lat: 12.9299, lng: 77.6849 },
    distanceKm: 0.2,
    open24x7: true,
    openingHours: '24 Hours / 7 Days',
    rating: 4.9
  },
  {
    id: 'ph-02',
    name: 'Apollo Pharmacy - Ring Road Junction',
    address: 'Shop 4, Outer Ring Road, Near EcoWorld',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560103',
    phone: '+91 80 2574 1120',
    coordinates: { lat: 12.9280, lng: 77.6810 },
    distanceKm: 0.9,
    open24x7: true,
    openingHours: '24 Hours / 7 Days',
    rating: 4.7
  },
  {
    id: 'ph-03',
    name: 'MedPlus Health Services - Bellandur Lake Rd',
    address: 'Plot 12, Bellandur Lake Road',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560103',
    phone: '+91 80 4122 8890',
    coordinates: { lat: 12.9320, lng: 77.6770 },
    distanceKm: 1.6,
    open24x7: false,
    openingHours: '07:30 AM - 11:30 PM',
    rating: 4.6
  },
  {
    id: 'ph-04',
    name: 'Wellness Forever Chemists & Superstore',
    address: 'Block A, Central Boulevard, Sarjapur Road',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560102',
    phone: '+91 80 6712 9900',
    coordinates: { lat: 12.9210, lng: 77.6720 },
    distanceKm: 2.8,
    open24x7: true,
    openingHours: '24 Hours / 7 Days',
    rating: 4.8
  }
];

export const SEED_INVENTORY = [
  {
    id: 'inv-01',
    pharmacyId: 'ph-01',
    pharmacyName: 'CareBridge 24x7 In-Hospital Pharmacy',
    pharmacyAddress: 'Outer Ring Road, Bellandur, Bengaluru',
    pharmacyPhone: '+91 80 4910 2150',
    distanceKm: 0.2,
    medicineId: 'med-01',
    medicineName: 'Dolo 650',
    genericName: 'Paracetamol 650 mg',
    dosageForm: 'Tablet',
    status: 'IN_STOCK',
    quantity: 450,
    unitPrice: 32.50,
    lastUpdated: '2026-09-20T10:00:00Z'
  },
  {
    id: 'inv-02',
    pharmacyId: 'ph-02',
    pharmacyName: 'Apollo Pharmacy - Ring Road Junction',
    pharmacyAddress: 'Outer Ring Road, Near EcoWorld, Bengaluru',
    pharmacyPhone: '+91 80 2574 1120',
    distanceKm: 0.9,
    medicineId: 'med-01',
    medicineName: 'Dolo 650',
    genericName: 'Paracetamol 650 mg',
    dosageForm: 'Tablet',
    status: 'IN_STOCK',
    quantity: 120,
    unitPrice: 33.00,
    lastUpdated: '2026-09-20T09:30:00Z'
  },
  {
    id: 'inv-03',
    pharmacyId: 'ph-01',
    pharmacyName: 'CareBridge 24x7 In-Hospital Pharmacy',
    pharmacyAddress: 'Outer Ring Road, Bellandur, Bengaluru',
    pharmacyPhone: '+91 80 4910 2150',
    distanceKm: 0.2,
    medicineId: 'med-02',
    medicineName: 'Augmentin 625 Duo',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    dosageForm: 'Tablet',
    status: 'IN_STOCK',
    quantity: 85,
    unitPrice: 204.00,
    lastUpdated: '2026-09-20T10:00:00Z'
  },
  {
    id: 'inv-04',
    pharmacyId: 'ph-02',
    pharmacyName: 'Apollo Pharmacy - Ring Road Junction',
    pharmacyAddress: 'Outer Ring Road, Near EcoWorld, Bengaluru',
    pharmacyPhone: '+91 80 2574 1120',
    distanceKm: 0.9,
    medicineId: 'med-02',
    medicineName: 'Augmentin 625 Duo',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    dosageForm: 'Tablet',
    status: 'LOW_STOCK',
    quantity: 12,
    unitPrice: 208.00,
    lastUpdated: '2026-09-20T09:30:00Z'
  },
  {
    id: 'inv-05',
    pharmacyId: 'ph-03',
    pharmacyName: 'MedPlus Health Services - Bellandur Lake Rd',
    pharmacyAddress: 'Bellandur Lake Road, Bengaluru',
    pharmacyPhone: '+91 80 4122 8890',
    distanceKm: 1.6,
    medicineId: 'med-02',
    medicineName: 'Augmentin 625 Duo',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    dosageForm: 'Tablet',
    status: 'OUT_OF_STOCK',
    quantity: 0,
    unitPrice: 204.00,
    lastUpdated: '2026-09-20T08:00:00Z'
  },
  {
    id: 'inv-06',
    pharmacyId: 'ph-01',
    pharmacyName: 'CareBridge 24x7 In-Hospital Pharmacy',
    pharmacyAddress: 'Outer Ring Road, Bellandur, Bengaluru',
    pharmacyPhone: '+91 80 4910 2150',
    distanceKm: 0.2,
    medicineId: 'med-03',
    medicineName: 'Glycomet 500 SR',
    genericName: 'Metformin Hydrochloride (Sustained Release)',
    dosageForm: 'Tablet',
    status: 'IN_STOCK',
    quantity: 210,
    unitPrice: 48.00,
    lastUpdated: '2026-09-20T10:00:00Z'
  },
  {
    id: 'inv-07',
    pharmacyId: 'ph-01',
    pharmacyName: 'CareBridge 24x7 In-Hospital Pharmacy',
    pharmacyAddress: 'Outer Ring Road, Bellandur, Bengaluru',
    pharmacyPhone: '+91 80 4910 2150',
    distanceKm: 0.2,
    medicineId: 'med-04',
    medicineName: 'Telma 40',
    genericName: 'Telmisartan 40 mg',
    dosageForm: 'Tablet',
    status: 'IN_STOCK',
    quantity: 140,
    unitPrice: 125.00,
    lastUpdated: '2026-09-20T10:00:00Z'
  },
  {
    id: 'inv-08',
    pharmacyId: 'ph-02',
    pharmacyName: 'Apollo Pharmacy - Ring Road Junction',
    pharmacyAddress: 'Outer Ring Road, Near EcoWorld, Bengaluru',
    pharmacyPhone: '+91 80 2574 1120',
    distanceKm: 0.9,
    medicineId: 'med-04',
    medicineName: 'Telma 40',
    genericName: 'Telmisartan 40 mg',
    dosageForm: 'Tablet',
    status: 'LOW_STOCK',
    quantity: 15,
    unitPrice: 127.00,
    lastUpdated: '2026-09-20T09:30:00Z'
  },
  {
    id: 'inv-09',
    pharmacyId: 'ph-01',
    pharmacyName: 'CareBridge 24x7 In-Hospital Pharmacy',
    pharmacyAddress: 'Outer Ring Road, Bellandur, Bengaluru',
    pharmacyPhone: '+91 80 4910 2150',
    distanceKm: 0.2,
    medicineId: 'med-08',
    medicineName: 'Budecort 200 Inhaler',
    genericName: 'Budesonide Inhalation Aerosol',
    dosageForm: 'Inhaler',
    status: 'IN_STOCK',
    quantity: 25,
    unitPrice: 345.00,
    lastUpdated: '2026-09-20T10:00:00Z'
  },
  {
    id: 'inv-10',
    pharmacyId: 'ph-01',
    pharmacyName: 'CareBridge 24x7 In-Hospital Pharmacy',
    pharmacyAddress: 'Outer Ring Road, Bellandur, Bengaluru',
    pharmacyPhone: '+91 80 4910 2150',
    distanceKm: 0.2,
    medicineId: 'med-10',
    medicineName: 'Lantus Solostar Pen',
    genericName: 'Insulin Glargine',
    dosageForm: 'Injection',
    status: 'LOW_STOCK',
    quantity: 8,
    unitPrice: 620.00,
    lastUpdated: '2026-09-20T10:00:00Z'
  }
];

export const SEED_APPOINTMENTS = [
  {
    id: 'apt-001',
    bookingReference: 'CB-2026-99412',
    patientId: 'pat-ramesh',
    patientName: 'Ramesh Kumar',
    patientPhone: '+91 94150 12345',
    doctorId: 'doc-sharma',
    doctorName: 'Dr. Anita Sharma',
    doctorSpecialty: 'Cardiology',
    doctorAvatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    hospitalId: 'hosp-01',
    hospitalName: 'CareBridge Apex Super-Specialty Hospital',
    hospitalAddress: '42 Outer Ring Road, Bellandur, Bengaluru',
    date: '2026-09-24',
    timeSlot: '10:30 AM',
    type: 'in_person',
    status: 'confirmed',
    fee: 800,
    paymentStatus: 'paid',
    notes: 'Quarterly review for hypertension and glycemic monitoring. Token CB-14.',
    createdAt: '2026-09-20T08:00:00Z'
  },
  {
    id: 'apt-002',
    bookingReference: 'CB-2026-99384',
    patientId: 'pat-ramesh',
    patientName: 'Ramesh Kumar',
    patientPhone: '+91 94150 12345',
    doctorId: 'doc-verma',
    doctorName: 'Dr. Rajesh Verma',
    doctorSpecialty: 'Orthopedics & Joint Care',
    doctorAvatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    hospitalId: 'hosp-05',
    hospitalName: 'CareBridge Metro Multi-Specialty Hospital',
    hospitalAddress: 'Link Road, Andheri West, Mumbai',
    date: '2026-09-22',
    timeSlot: '04:00 PM',
    type: 'teleconsultation',
    status: 'confirmed',
    fee: 700,
    paymentStatus: 'paid',
    notes: 'Bilateral knee stiffness evaluation. Teleconsultation video session.',
    createdAt: '2026-09-19T14:20:00Z'
  },
  {
    id: 'apt-003',
    bookingReference: 'CB-2026-98210',
    patientId: 'pat-sunita',
    patientName: 'Sunita Devi',
    patientPhone: '+91 94150 67890',
    doctorId: 'doc-chatterjee',
    doctorName: 'Dr. Sunita Chatterjee',
    doctorSpecialty: 'Obstetrics & Gynecology',
    doctorAvatarUrl: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=400&auto=format&fit=crop&q=80',
    hospitalId: 'hosp-03',
    hospitalName: 'CareBridge Women & Children\'s Pavilion',
    hospitalAddress: '18 Institutional Area, Sheikh Sarai, New Delhi',
    date: '2026-09-23',
    timeSlot: '11:00 AM',
    type: 'in_person',
    status: 'confirmed',
    fee: 850,
    paymentStatus: 'paid',
    notes: 'Third trimester routine antenatal checkup. Token CB-08.',
    createdAt: '2026-09-18T10:00:00Z'
  }
];

export const SEED_PRESCRIPTIONS = [
  {
    id: 'rx-9901',
    appointmentId: 'apt-001',
    patientId: 'pat-ramesh',
    patientName: 'Ramesh Kumar',
    patientAge: 52,
    patientGender: 'Male',
    doctorId: 'doc-sharma',
    doctorName: 'Dr. Anita Sharma',
    doctorRegistration: 'MCI/UP/2012/048821',
    doctorSpecialty: 'Cardiology',
    hospitalName: 'CareBridge Apex Super-Specialty Hospital',
    date: '2026-08-15',
    diagnosis: ['Primary Essential Hypertension (Stage 1)', 'Type 2 Diabetes Mellitus (Managed)'],
    vitals: {
      bloodPressure: '128/82 mmHg',
      pulseBpm: 72,
      spo2: 98,
      temperatureF: 98.4
    },
    medicines: [
      {
        id: 'rx-m1',
        medicineName: 'Telma 40 (Telmisartan 40mg)',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Morning)',
        duration: '90 Days',
        instructions: 'Take in the morning after breakfast with water.'
      },
      {
        id: 'rx-m2',
        medicineName: 'Glycomet 500 SR (Metformin 500mg)',
        dosage: '1 Tablet',
        frequency: 'Twice Daily (Morning & Night)',
        duration: '90 Days',
        instructions: 'Take immediately with meals.'
      }
    ],
    advice: 'Restrict dietary sodium to under 3g/day. 30 minutes of brisk morning walking. Monitor fasting glucose weekly.',
    followUpDate: '2026-11-15',
    doctorSignatureStamp: 'SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    createdAt: '2026-08-15T11:45:00Z'
  }
];

export const SEED_NOTIFICATIONS = [
  {
    id: 'notif-01',
    userId: 'pat-ramesh',
    title: 'Upcoming Cardiology Appointment',
    message: 'Your in-person consultation with Dr. Anita Sharma is scheduled for Sep 24, 10:30 AM at CareBridge Apex Hospital. Token: CB-14.',
    category: 'appointment',
    read: false,
    actionUrl: '/appointments',
    createdAt: '2026-09-20T08:05:00Z'
  },
  {
    id: 'notif-02',
    userId: 'pat-ramesh',
    title: 'Teleconsultation Video Link Active',
    message: 'Your video room link with Dr. Rajesh Verma is ready. Consultation starts tomorrow at 04:00 PM.',
    category: 'teleconsult',
    read: false,
    actionUrl: '/teleconsult/CB-ROOM-99384',
    createdAt: '2026-09-19T14:22:00Z'
  },
  {
    id: 'notif-03',
    userId: 'pat-ramesh',
    title: 'Digital Prescription Available',
    message: 'Dr. Anita Sharma has issued your updated 90-day maintenance prescription. View or print anytime.',
    category: 'prescription',
    read: true,
    actionUrl: '/prescriptions/rx-9901',
    createdAt: '2026-08-15T11:45:00Z'
  },
  {
    id: 'notif-04',
    userId: 'pat-ramesh',
    title: 'Security Alert: Access Verified',
    message: 'Clinical record access was securely authenticated by Dr. Anita Sharma during your OPD encounter.',
    category: 'security',
    read: true,
    actionUrl: '/patient/consents',
    createdAt: '2026-08-15T11:30:00Z'
  }
];
